In [1]:
import numpy as np

In [37]:
a = np.array([1,23,4,5,6,7,8,9,9,8,9,6] ,dtype ='float')

In [7]:
print(a)

[ 1. 23.  4.  5.  6.  7.  8.  9.  9.  8.  9.  6.]


In [5]:
print(a)

[ 1 23  4  5  6  7  8  9  9  8  9  6]


In [24]:
b = np.array([[[1],23,3], [1,2,3] , [2,a,2]])
print(b)

[[list([1]) 23 3]
 [1 2 3]
 [2 array([ 1., 23.,  4.,  5.,  6.,  7.,  8.,  9.,  9.,  8.,  9.,  6.]) 2]]


In [25]:
b.ndim

2

In [28]:
b[2][1].shape

(12,)

In [31]:
a.dtype

dtype('float64')

In [34]:
b[2].itemsize

8

In [36]:
b.nbytes

72

In [3]:
f = np.array([[[1,2,3] , [1,2,3], [4,5,6]],[[2,3,4] ,[3,4,5] , [3,4,5]] , [[5,6,7],[4,5,6],[6,7,8]]])
print(f)

[[[1 2 3]
  [1 2 3]
  [4 5 6]]

 [[2 3 4]
  [3 4 5]
  [3 4 5]]

 [[5 6 7]
  [4 5 6]
  [6 7 8]]]


In [4]:
f.dtype

dtype('int32')

In [6]:
f.shape

(3, 3, 3)

In [10]:
f.ndim

3

In [16]:
print(f[ 1, 1 ,:])

[3 4 5]


In [24]:
q = np.zeros((3, 3, 3))
print(q)

[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]


In [25]:
#all 1s matrix
w = np.ones((3,3,3))

In [26]:
print(w)

[[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]]


# any other value

In [27]:

a = np.full((3,3,3) , 90)
print(a)

[[[90 90 90]
  [90 90 90]
  [90 90 90]]

 [[90 90 90]
  [90 90 90]
  [90 90 90]]

 [[90 90 90]
  [90 90 90]
  [90 90 90]]]


# full like method

In [31]:

e=np.full_like( f ,50)
print(e)

[[[50 50 50]
  [50 50 50]
  [50 50 50]]

 [[50 50 50]
  [50 50 50]
  [50 50 50]]

 [[50 50 50]
  [50 50 50]
  [50 50 50]]]


# random number start array 

In [38]:

r = np.random.rand(3,3)*10
print(r)

[[9.72976122 7.41643025 7.37240579]
 [0.48153487 6.78206932 2.7514262 ]
 [5.30896956 8.12234453 4.70987918]]


# random interger value 

In [44]:

t = np.random.randint(0 , 2, size =(4,4))
print(t)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


# identity matix

In [45]:

y = np.identity(4)
print(y)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


# reapit array 

In [74]:

arr = np.array([1,2,3])
r1 = np.repeat(arr , 3 , axis = 0)
print("r1 = ")
print(r1)

arr1 = np.array([[1,2,3]])
r2 = np.repeat(arr1 , 3 , axis = 0)
print("r2 = ")
print(r2)


#if i change axis then


r1 = 
[1 1 1 2 2 2 3 3 3]
r2 = 
[[1 2 3]
 [1 2 3]
 [1 2 3]]


# heree the axix is basically tell about from which dimention we want to repeat array like 0  means 3-d , 1 mean first inner box ,2 eans inside last bracket

In [73]:
arr2 = np.array([[[1,2,3] , [4,5,6]] , [[2,3,4],[5,6,7]] , [[3,4,5],[6,7,8]]])
r3= np.repeat(arr2 , 2 , axis = 2)
print("r3 =" , r3)

r3 = [[[1 1 2 2 3 3]
  [4 4 5 5 6 6]]

 [[2 2 3 3 4 4]
  [5 5 6 6 7 7]]

 [[3 3 4 4 5 5]
  [6 6 7 7 8 8]]]


# coping one array to another with specified location

In [72]:


final = np.ones((5,5))
print(final)
chg = np.zeros((3,3))
chg[1][1] = 9
print(chg)

final[1 : 4 , 1 :4] = chg
print(final)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


# be careful in copying 



In [61]:
a = np.array([1,23,3])
b = a 
b[0] = 100
print(a)

[100  23   3]


# mathematics

In [63]:
a = np.array([1,2,3])
print(a)

[1 2 3]


In [64]:
a +2

array([3, 4, 5])

In [65]:
a - 2

array([-1,  0,  1])

In [66]:
a / 2

array([0.5, 1. , 1.5])

In [67]:
a * 2

array([2, 4, 6])

In [68]:
a ** 3 #quab of array


array([ 1,  8, 27], dtype=int32)

In [69]:
b  =np.array([3,4,5])
a + b

array([4, 6, 8])

In [70]:
np.sin(a)

array([0.84147098, 0.90929743, 0.14112001])

In [71]:
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 ])

# linear algebra

In [79]:
a = np.full((2,3)  , 2)
print(a)

b = np.full((3,2) , 3)
print(b)

[[2 2 2]
 [2 2 2]]
[[3 3]
 [3 3]
 [3 3]]


# matrix multiplication

In [80]:
c = np.matmul(a ,b)
print(c)

[[18 18]
 [18 18]]


In [85]:
c[1][1] = 19.0
#find the determinent of matrix
np.linalg.det(c)

17.999999999999996

In [86]:
## Reference docs (https://docs.scipy.org/doc/numpy/reference/routines.linalg.html)

# Determinant
# Trace
# Singular Vector Decomposition
# Eigenvalues
# Matrix Norm
# Inverse
# Etc...

# statistic

In [100]:
stat = np.array([[7,2,1] ,
               [4,5,3]])
print(stat)

[[7 2 1]
 [4 5 3]]


In [101]:
np.min(stat ,axis = 0)
### without axis it will give overall max and min
### in this the compare wit 7-> 4 , 2-->5 , 1-->3

array([4, 2, 1])

In [104]:
np.max(stat ,axis = 1 )
## it will compare (7,2,1) and (4,5,3) and give max from each bracket

array([7, 5])

# reorganising aray

In [118]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before) 

after = before.reshape((2,2,2))
print(after)

[[1 2 3 4]
 [5 6 7 8]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


# vertical stack array

In [119]:
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

In [122]:
np.vstack([v1,v2]) 

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

# horizontal stack 

In [121]:
np.hstack([v1,v2])

array([1, 2, 3, 4, 5, 6, 7, 8])

# Load data from file

In [139]:
filedata = np.genfromtxt('data.txt'  ,delimiter = ',')
filedat =filedata.astype('int')
print(filedata)

[[ 1.  2.  3.  4.  5.  6.  7.  8.  9.]
 [10. 11. 12. 13. 14. 15. 16. 17. 18.]
 [19. 20. 21. 22. 23. 24. 25. 26. 27.]
 [28. 29. 30. 31. 32. 33. 34. 35. 36.]]


## boolean masking and advance indexing

In [141]:
filedata > 3 

array([[False, False, False,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True]])

In [144]:
filedata[filedata> 4]
##data where it is grater then 4

array([ 5.,  6.,  7.,  8.,  9., 10., 11., 12., 13., 14., 15., 16., 17.,
       18., 19., 20., 21., 22., 23., 24., 25., 26., 27., 28., 29., 30.,
       31., 32., 33., 34., 35., 36.])

In [149]:
a = np.array([123,1242,42545,344,345,6785,7653,5634])
a[[1,3,4,5]]

array([1242,  344,  345, 6785])

In [151]:
data = np.array([[1,13,21,11,196,75,4,3,34,6,7,8,0,1,2,3,4,5] , [3,42,12,33,766,75,4,55,6,4,3,4,5,6,7,0,11,12] , [1,22,33,11,999,11,2,1,78,0,1,2,9,8,7,1,76,88]])
print(data)

[[  1  13  21  11 196  75   4   3  34   6   7   8   0   1   2   3   4   5]
 [  3  42  12  33 766  75   4  55   6   4   3   4   5   6   7   0  11  12]
 [  1  22  33  11 999  11   2   1  78   0   1   2   9   8   7   1  76  88]]


In [154]:
np.any(data > 50 , axis = 0)
#this will give you that and of column data is > 50

array([False, False, False, False,  True,  True, False,  True,  True,
       False, False, False, False, False, False, False,  True,  True])

In [155]:
np.max(data)

999

In [157]:
np.all(data > 195 , axis =0)
#this will give you the column in which all the element are > 195 

array([False, False, False, False,  True, False, False, False, False,
       False, False, False, False, False, False, False, False, False])